# Generated by Django 4.1.5 on 2023-01-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_order_is_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified in'),
        ),
    ]
